name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build-test-lint:
    name: Lint + Test + Build API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black flake8

    - name: Run Linting (black & flake8)
      run: |
        black --check .
        flake8 .

    - name: Run Tests
      run: pytest -q

    - name: Build Docker image
      run: |
        docker build -t diabetes-api .

  push-image:
    name: Push Docker Image to GitHub Container Registry
    needs: build-test-lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Image Tag
      id: version
      run: echo "TAG=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/diabetes-api:${{ env.TAG }} .

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/diabetes-api:${{ env.TAG }}

  notify:
    name: Notify Build Result
    needs: [push-image]
    runs-on: ubuntu-latest

    steps:
    - name: Print Summary
      run: |
        echo "CI Pipeline Completed Successfully"
        echo "Image pushed to: ghcr.io/${{ github.repository_owner }}/diabetes-api:${{ env.TAG }}"
