name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Code (flake8)
      run: |
        pip install flake8
        flake8 --max-line-length=120 --exclude=venv,__pycache__

    - name: Run Unit Tests
      run: |
        pip install pytest coverage
        coverage run -m pytest
        coverage report -m

    - name: Build Docker Image
      run: |
        docker build -t diabetes_prediction_api ./api

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
